export type MaterialRate = {
  id: string;
  type: string;
  material: string;
  thickness: number | null;
  feed: number | null;
  density: number | null;
  cutRate: number | null;
  costPerM2: number | null;
  piercingRate: number | null;
  piercingTime: number | null;
};

export const materialRates: MaterialRate[] = [
  {
    "id": "mat-4",
    "type": "ALUMINIUM",
    "material": "ALFL/PL",
    "thickness": 2.5,
    "feed": 2500,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": null,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-182",
    "type": "ALUMINIUM",
    "material": "ALFL/PL",
    "thickness": 4.5,
    "feed": 1400,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-102",
    "type": "ALUMINIUM",
    "material": "ALFL/PL",
    "thickness": 5,
    "feed": 1400,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": null,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-143",
    "type": "ALUMINIUM",
    "material": "ALI 5005",
    "thickness": 0.6,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 18,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-136",
    "type": "ALUMINIUM",
    "material": "ALI 5005",
    "thickness": 1.2,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 33,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-25",
    "type": "ALUMINIUM",
    "material": "ALI 5005",
    "thickness": 1.6,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 41,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-46",
    "type": "ALUMINIUM",
    "material": "ALI 5005",
    "thickness": 2,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 50,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-48",
    "type": "ALUMINIUM",
    "material": "ALI 5005",
    "thickness": 2.5,
    "feed": 2000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 62,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-29",
    "type": "ALUMINIUM",
    "material": "ALI 5005",
    "thickness": 3,
    "feed": 1900,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 91,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-16",
    "type": "ALUMINIUM",
    "material": "ALI 5005",
    "thickness": 4,
    "feed": 1500,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 97,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-144",
    "type": "ALUMINIUM",
    "material": "ALI 5005",
    "thickness": 5,
    "feed": 1300,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 135,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-42",
    "type": "ALUMINIUM",
    "material": "ALI 5005",
    "thickness": 6,
    "feed": 1200,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 167,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-191",
    "type": "ALUMINIUM",
    "material": "ALI 5083",
    "thickness": 3,
    "feed": 1900,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 86,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-147",
    "type": "ALUMINIUM",
    "material": "ALI 5083",
    "thickness": 4,
    "feed": 1500,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 115,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-158",
    "type": "ALUMINIUM",
    "material": "ALI 5083",
    "thickness": 5,
    "feed": 1300,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 143,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-92",
    "type": "ALUMINIUM",
    "material": "ALI 5083",
    "thickness": 6,
    "feed": 1200,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 172,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-151",
    "type": "ALUMINIUM",
    "material": "ALI 5083",
    "thickness": 8,
    "feed": 750,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 233,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-128",
    "type": "ALUMINIUM",
    "material": "ALI 5083",
    "thickness": 10,
    "feed": 600,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 296,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-68",
    "type": "ALUMINIUM",
    "material": "ALI 5083",
    "thickness": 12,
    "feed": 400,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 343,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-120",
    "type": "ALUMINIUM",
    "material": "ALI 5083",
    "thickness": 16,
    "feed": 400,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 460,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-199",
    "type": "ALUMINIUM",
    "material": "ALI 5083",
    "thickness": 20,
    "feed": 200,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 573,
    "piercingRate": 10,
    "piercingTime": null
  },
  {
    "id": "mat-2",
    "type": "ALUMINIUM",
    "material": "ALI 6061",
    "thickness": 5,
    "feed": null,
    "density": null,
    "cutRate": 0,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-104",
    "type": "ALUMINIUM",
    "material": "PERF ALI",
    "thickness": 1.6,
    "feed": 3000,
    "density": null,
    "cutRate": 6,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-180",
    "type": "BRASS / COPPER TYPE",
    "material": "BRASS",
    "thickness": 1.2,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-51",
    "type": "BRASS / COPPER TYPE",
    "material": "BRASS",
    "thickness": 1.6,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-106",
    "type": "Chromoly Steel",
    "material": "CHRMOLY",
    "thickness": 6,
    "feed": 1600,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-7",
    "type": "Chromoly Steel",
    "material": "CREUSABRO",
    "thickness": 0,
    "feed": null,
    "density": null,
    "cutRate": 0,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-112",
    "type": "Duplex Stainless Steel",
    "material": "SAF 2205",
    "thickness": 0,
    "feed": null,
    "density": null,
    "cutRate": 0,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-188",
    "type": "Galvanised Steel",
    "material": "ELECTOGALV",
    "thickness": 1.2,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 32,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-189",
    "type": "Galvanised Steel",
    "material": "ELECTOGALV",
    "thickness": 1.55,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 40.5,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-190",
    "type": "Galvanised Steel",
    "material": "ELECTOGALV",
    "thickness": 2,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 51,
    "piercingRate": null,
    "piercingTime": null
  },
  {
    "id": "mat-103",
    "type": "Galvanised Steel",
    "material": "GALV",
    "thickness": 0.5,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 17,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-121",
    "type": "Galvanised Steel",
    "material": "GALV",
    "thickness": 1,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 26,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-28",
    "type": "Galvanised Steel",
    "material": "GALV",
    "thickness": 1.2,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 31,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-145",
    "type": "Galvanised Steel",
    "material": "GALV",
    "thickness": 1.6,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 40.5,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-168",
    "type": "Galvanised Steel",
    "material": "GALV",
    "thickness": 2,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 51,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-30",
    "type": "Galvanised Steel",
    "material": "GALV",
    "thickness": 2.5,
    "feed": 2300,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 65,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-72",
    "type": "Galvanised Steel",
    "material": "GALV",
    "thickness": 3,
    "feed": 2000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 80,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-157",
    "type": "High Strength Steel",
    "material": "400BIS",
    "thickness": 5,
    "feed": 1700,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-82",
    "type": "High Strength Steel",
    "material": "400BIS",
    "thickness": 6,
    "feed": 1500,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-111",
    "type": "High Strength Steel",
    "material": "500 BIS",
    "thickness": 12,
    "feed": 900,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-166",
    "type": "High Strength Steel",
    "material": "500 BIS",
    "thickness": 16,
    "feed": 650,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-119",
    "type": "High Strength Steel",
    "material": "80 BIS",
    "thickness": 6,
    "feed": 1500,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": null,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-91",
    "type": "High Strength Steel",
    "material": "80 BIS",
    "thickness": 8,
    "feed": 1200,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": null,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-89",
    "type": "High Strength Steel",
    "material": "80 BIS",
    "thickness": 10,
    "feed": 1000,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-31",
    "type": "High Strength Steel",
    "material": "80 BIS",
    "thickness": 12,
    "feed": 900,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": null,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-8",
    "type": "High Strength Steel",
    "material": "80 BIS",
    "thickness": 16,
    "feed": 650,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": null,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-107",
    "type": "High Strength Steel",
    "material": "80 BIS",
    "thickness": 20,
    "feed": 550,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": null,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-56",
    "type": "High Strength Steel",
    "material": "80 BIS",
    "thickness": 25,
    "feed": 700,
    "density": null,
    "cutRate": 7,
    "costPerM2": null,
    "piercingRate": 6,
    "piercingTime": null
  },
  {
    "id": "mat-183",
    "type": "High Strength Steel",
    "material": "STRENX 700",
    "thickness": 3,
    "feed": 2300,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 75,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-184",
    "type": "High Strength Steel",
    "material": "STRENX 700",
    "thickness": 4,
    "feed": 1900,
    "density": null,
    "cutRate": 4.4,
    "costPerM2": 85,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-185",
    "type": "High Strength Steel",
    "material": "STRENX 700",
    "thickness": 5,
    "feed": 1700,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 106,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-186",
    "type": "High Strength Steel",
    "material": "STRENX 700",
    "thickness": 6,
    "feed": 1500,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 128,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-187",
    "type": "High Strength Steel",
    "material": "STRENX 700",
    "thickness": 8,
    "feed": 1200,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 170,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-159",
    "type": "Nickel Alloy",
    "material": "INCONEL",
    "thickness": 0,
    "feed": null,
    "density": null,
    "cutRate": 0,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-100",
    "type": "SPECIAL MATERIALS",
    "material": "CORTEN",
    "thickness": 3,
    "feed": 2000,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": null,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-11",
    "type": "SPECIAL MATERIALS",
    "material": "CORTEN",
    "thickness": 5,
    "feed": 1700,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": null,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-23",
    "type": "STAINLESS STEEL",
    "material": "304 FLPL",
    "thickness": 6,
    "feed": 1200,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 400,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-131",
    "type": "STAINLESS STEEL",
    "material": "304 S/S",
    "thickness": 0.6,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 49,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-152",
    "type": "STAINLESS STEEL",
    "material": "304 S/S",
    "thickness": 0.7,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 60,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-98",
    "type": "STAINLESS STEEL",
    "material": "304 S/S",
    "thickness": 0.9,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 75,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-97",
    "type": "STAINLESS STEEL",
    "material": "304 S/S",
    "thickness": 1.2,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 100,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-22",
    "type": "STAINLESS STEEL",
    "material": "304 S/S",
    "thickness": 1.6,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 120,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-148",
    "type": "STAINLESS STEEL",
    "material": "304 S/S",
    "thickness": 2,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 160,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-101",
    "type": "STAINLESS STEEL",
    "material": "304 S/S",
    "thickness": 2.5,
    "feed": 2500,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 205,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-62",
    "type": "STAINLESS STEEL",
    "material": "304 S/S",
    "thickness": 3,
    "feed": 2000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 235,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-140",
    "type": "STAINLESS STEEL",
    "material": "304 S/S",
    "thickness": 4,
    "feed": 1500,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 345,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-80",
    "type": "STAINLESS STEEL",
    "material": "304 S/S",
    "thickness": 5,
    "feed": 1400,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 435,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-59",
    "type": "STAINLESS STEEL",
    "material": "304 S/S",
    "thickness": 6,
    "feed": 1200,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 520,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-125",
    "type": "STAINLESS STEEL",
    "material": "304 S/S",
    "thickness": 8,
    "feed": 750,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 620,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-109",
    "type": "STAINLESS STEEL",
    "material": "304 S/S",
    "thickness": 10,
    "feed": 600,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 780,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-124",
    "type": "STAINLESS STEEL",
    "material": "304 S/S",
    "thickness": 12,
    "feed": 450,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 900,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-123",
    "type": "STAINLESS STEEL",
    "material": "304 S/S",
    "thickness": 16,
    "feed": 350,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 1215,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-110",
    "type": "STAINLESS STEEL",
    "material": "304 S/S",
    "thickness": 20,
    "feed": 250,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 1520,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-85",
    "type": "STAINLESS STEEL",
    "material": "304 S/S",
    "thickness": 25,
    "feed": 200,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 2600,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-60",
    "type": "STAINLESS STEEL",
    "material": "304-4",
    "thickness": 0.9,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 73,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-84",
    "type": "STAINLESS STEEL",
    "material": "304-4",
    "thickness": 1.2,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 95,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-55",
    "type": "STAINLESS STEEL",
    "material": "304-4",
    "thickness": 1.6,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 120,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-6",
    "type": "STAINLESS STEEL",
    "material": "304-4",
    "thickness": 2,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 160,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-155",
    "type": "STAINLESS STEEL",
    "material": "304-4",
    "thickness": 3,
    "feed": 2000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 235,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-139",
    "type": "STAINLESS STEEL",
    "material": "304-8",
    "thickness": 2,
    "feed": 3000,
    "density": null,
    "cutRate": 7,
    "costPerM2": null,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-32",
    "type": "STAINLESS STEEL",
    "material": "304-8",
    "thickness": 3,
    "feed": 2000,
    "density": null,
    "cutRate": 7,
    "costPerM2": null,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-90",
    "type": "STAINLESS STEEL",
    "material": "316 - 4",
    "thickness": 1.2,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 112,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-40",
    "type": "STAINLESS STEEL",
    "material": "316 - 4",
    "thickness": 1.6,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 137,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-127",
    "type": "STAINLESS STEEL",
    "material": "316 - 4",
    "thickness": 2,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 172,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-165",
    "type": "STAINLESS STEEL",
    "material": "316 - 4",
    "thickness": 3,
    "feed": 2000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 242,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-70",
    "type": "STAINLESS STEEL",
    "material": "316 FLPL",
    "thickness": 0,
    "feed": 3400,
    "density": null,
    "cutRate": 0,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-193",
    "type": "STAINLESS STEEL",
    "material": "316-4",
    "thickness": 0.9,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 95,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-194",
    "type": "STAINLESS STEEL",
    "material": "316-4",
    "thickness": 1.2,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 120,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-195",
    "type": "STAINLESS STEEL",
    "material": "316-4",
    "thickness": 1.6,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 150,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-196",
    "type": "STAINLESS STEEL",
    "material": "316-4",
    "thickness": 2,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 195,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-197",
    "type": "STAINLESS STEEL",
    "material": "316-4",
    "thickness": 3,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 290,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-54",
    "type": "STAINLESS STEEL",
    "material": "3CR12",
    "thickness": 3,
    "feed": 2000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-171",
    "type": "STAINLESS STEEL",
    "material": "904 S/S",
    "thickness": 0,
    "feed": null,
    "density": null,
    "cutRate": 0,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-135",
    "type": "STAINLESS STEEL",
    "material": "FLOORPLATE",
    "thickness": 3,
    "feed": 2000,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 75,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-69",
    "type": "STAINLESS STEEL",
    "material": "FLOORPLATE",
    "thickness": 5,
    "feed": 1700,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 120,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-49",
    "type": "STAINLESS STEEL",
    "material": "FLOORPLATE",
    "thickness": 6,
    "feed": 1500,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 143,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-81",
    "type": "STAINLESS STEEL",
    "material": "FLOORPLATE",
    "thickness": 8,
    "feed": 1200,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-192",
    "type": "STAINLESS STEEL",
    "material": "FLOORPLATE",
    "thickness": 10,
    "feed": 1000,
    "density": null,
    "cutRate": 7,
    "costPerM2": null,
    "piercingRate": 0.5,
    "piercingTime": null
  },
  {
    "id": "mat-65",
    "type": "STAINLESS STEEL",
    "material": "RIMEX",
    "thickness": 1.2,
    "feed": 3000,
    "density": null,
    "cutRate": 7,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-181",
    "type": "STAINLESS STEEL",
    "material": "S/S 316",
    "thickness": 0.55,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 56,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-177",
    "type": "STAINLESS STEEL",
    "material": "S/S 316",
    "thickness": 0.7,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 72,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-169",
    "type": "STAINLESS STEEL",
    "material": "S/S 316",
    "thickness": 0.9,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 92,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-17",
    "type": "STAINLESS STEEL",
    "material": "S/S 316",
    "thickness": 1.2,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 120,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-21",
    "type": "STAINLESS STEEL",
    "material": "S/S 316",
    "thickness": 1.6,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 150,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-14",
    "type": "STAINLESS STEEL",
    "material": "S/S 316",
    "thickness": 2,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 195,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-61",
    "type": "STAINLESS STEEL",
    "material": "S/S 316",
    "thickness": 2.5,
    "feed": 2500,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 240,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-156",
    "type": "STAINLESS STEEL",
    "material": "S/S 316",
    "thickness": 3,
    "feed": 2000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 290,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-116",
    "type": "STAINLESS STEEL",
    "material": "S/S 316",
    "thickness": 4,
    "feed": 1500,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 445,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-132",
    "type": "STAINLESS STEEL",
    "material": "S/S 316",
    "thickness": 5,
    "feed": 1400,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 535,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-161",
    "type": "STAINLESS STEEL",
    "material": "S/S 316",
    "thickness": 6,
    "feed": 1200,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 645,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-76",
    "type": "STAINLESS STEEL",
    "material": "S/S 316",
    "thickness": 8,
    "feed": 750,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 835,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-67",
    "type": "STAINLESS STEEL",
    "material": "S/S 316",
    "thickness": 10,
    "feed": 600,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 1045,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-134",
    "type": "STAINLESS STEEL",
    "material": "S/S 316",
    "thickness": 12,
    "feed": 450,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 1195,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-162",
    "type": "STAINLESS STEEL",
    "material": "S/S 316",
    "thickness": 16,
    "feed": 350,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 1770,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-129",
    "type": "STAINLESS STEEL",
    "material": "S/S 316",
    "thickness": 20,
    "feed": 250,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 2210,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-96",
    "type": "STAINLESS STEEL",
    "material": "S/S 316",
    "thickness": 25,
    "feed": 200,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 3500,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-167",
    "type": "STEEL",
    "material": "GR 350",
    "thickness": 3,
    "feed": 2300,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": null,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-178",
    "type": "STEEL",
    "material": "GR 350",
    "thickness": 4,
    "feed": 1900,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 93,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-126",
    "type": "STEEL",
    "material": "GR 350",
    "thickness": 5,
    "feed": 1700,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 118,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-63",
    "type": "STEEL",
    "material": "GR 350",
    "thickness": 6,
    "feed": 1500,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 140,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-141",
    "type": "STEEL",
    "material": "GR 350",
    "thickness": 8,
    "feed": 1200,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 185,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-122",
    "type": "STEEL",
    "material": "GR 350",
    "thickness": 10,
    "feed": 1000,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 232,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-172",
    "type": "STEEL",
    "material": "GR 350",
    "thickness": 12,
    "feed": 900,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 278,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-95",
    "type": "STEEL",
    "material": "GR 350",
    "thickness": 16,
    "feed": 650,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 390,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-10",
    "type": "STEEL",
    "material": "GR 350",
    "thickness": 20,
    "feed": 550,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 487,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-114",
    "type": "STEEL",
    "material": "GR 350",
    "thickness": 25,
    "feed": null,
    "density": null,
    "cutRate": null,
    "costPerM2": null,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-71",
    "type": "STEEL",
    "material": "GR 350 P",
    "thickness": 6,
    "feed": 2500,
    "density": null,
    "cutRate": 7,
    "costPerM2": 152,
    "piercingRate": 0.5,
    "piercingTime": null
  },
  {
    "id": "mat-66",
    "type": "STEEL",
    "material": "GR 350 P",
    "thickness": 8,
    "feed": 2000,
    "density": null,
    "cutRate": 7,
    "costPerM2": 187,
    "piercingRate": 0.5,
    "piercingTime": null
  },
  {
    "id": "mat-93",
    "type": "STEEL",
    "material": "GR 350 P",
    "thickness": 10,
    "feed": 1600,
    "density": null,
    "cutRate": 7,
    "costPerM2": 226,
    "piercingRate": 0.5,
    "piercingTime": null
  },
  {
    "id": "mat-133",
    "type": "STEEL",
    "material": "GR 350 P",
    "thickness": 12,
    "feed": 1500,
    "density": null,
    "cutRate": 7,
    "costPerM2": 267,
    "piercingRate": 0.5,
    "piercingTime": null
  },
  {
    "id": "mat-113",
    "type": "STEEL",
    "material": "GR 350 P",
    "thickness": 16,
    "feed": 1200,
    "density": null,
    "cutRate": 7,
    "costPerM2": 352,
    "piercingRate": 1,
    "piercingTime": null
  },
  {
    "id": "mat-47",
    "type": "STEEL",
    "material": "GR 350 P",
    "thickness": 20,
    "feed": 1100,
    "density": null,
    "cutRate": 7,
    "costPerM2": 437,
    "piercingRate": 1,
    "piercingTime": null
  },
  {
    "id": "mat-108",
    "type": "STEEL",
    "material": "GR 350 P",
    "thickness": 25,
    "feed": 900,
    "density": null,
    "cutRate": 7,
    "costPerM2": 536,
    "piercingRate": 1,
    "piercingTime": null
  },
  {
    "id": "mat-19",
    "type": "STEEL",
    "material": "GR 350 P",
    "thickness": 32,
    "feed": 650,
    "density": null,
    "cutRate": 7,
    "costPerM2": 685,
    "piercingRate": 1.5,
    "piercingTime": null
  },
  {
    "id": "mat-179",
    "type": "STEEL",
    "material": "GR 350 P",
    "thickness": 40,
    "feed": 600,
    "density": null,
    "cutRate": 7,
    "costPerM2": 862,
    "piercingRate": 2.5,
    "piercingTime": null
  },
  {
    "id": "mat-52",
    "type": "STEEL",
    "material": "GR 350 P",
    "thickness": 50,
    "feed": 400,
    "density": null,
    "cutRate": 7,
    "costPerM2": 1077,
    "piercingRate": 3,
    "piercingTime": null
  },
  {
    "id": "mat-15",
    "type": "STEEL",
    "material": "GR 350 P",
    "thickness": 60,
    "feed": 300,
    "density": null,
    "cutRate": 7,
    "costPerM2": 1405,
    "piercingRate": 3,
    "piercingTime": null
  },
  {
    "id": "mat-130",
    "type": "STEEL",
    "material": "HARDOX 450",
    "thickness": 3,
    "feed": 2300,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-13",
    "type": "STEEL",
    "material": "HARDOX 450",
    "thickness": 4,
    "feed": 1900,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-164",
    "type": "STEEL",
    "material": "HARDOX 450",
    "thickness": 5,
    "feed": 1700,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-174",
    "type": "STEEL",
    "material": "HARDOX 450",
    "thickness": 6,
    "feed": 1500,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-160",
    "type": "STEEL",
    "material": "HARDOX 450",
    "thickness": 8,
    "feed": 1200,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-34",
    "type": "STEEL",
    "material": "HARDOX 450",
    "thickness": 10,
    "feed": 1000,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-57",
    "type": "STEEL",
    "material": "HARDOX 450",
    "thickness": 12,
    "feed": 900,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-83",
    "type": "STEEL",
    "material": "HARDOX 450",
    "thickness": 16,
    "feed": 650,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-118",
    "type": "STEEL",
    "material": "HARDOX 450",
    "thickness": 20,
    "feed": 550,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-105",
    "type": "steel",
    "material": "HARDX 450P",
    "thickness": 3,
    "feed": 2000,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 1,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-44",
    "type": "steel",
    "material": "HARDX 450P",
    "thickness": 5,
    "feed": 3500,
    "density": null,
    "cutRate": 7,
    "costPerM2": 1,
    "piercingRate": 2,
    "piercingTime": null
  },
  {
    "id": "mat-115",
    "type": "steel",
    "material": "HARDX 450P",
    "thickness": 6,
    "feed": 2500,
    "density": null,
    "cutRate": 7,
    "costPerM2": 1,
    "piercingRate": 2,
    "piercingTime": null
  },
  {
    "id": "mat-74",
    "type": "steel",
    "material": "HARDX 450P",
    "thickness": 8,
    "feed": 2000,
    "density": null,
    "cutRate": 7,
    "costPerM2": 1,
    "piercingRate": 2,
    "piercingTime": null
  },
  {
    "id": "mat-9",
    "type": "steel",
    "material": "HARDX 450P",
    "thickness": 10,
    "feed": 1600,
    "density": null,
    "cutRate": 7,
    "costPerM2": 1,
    "piercingRate": 2,
    "piercingTime": null
  },
  {
    "id": "mat-1",
    "type": "steel",
    "material": "HARDX 450P",
    "thickness": 12,
    "feed": 1500,
    "density": null,
    "cutRate": 7,
    "costPerM2": 1,
    "piercingRate": 2,
    "piercingTime": null
  },
  {
    "id": "mat-142",
    "type": "steel",
    "material": "HARDX 450P",
    "thickness": 16,
    "feed": 1200,
    "density": null,
    "cutRate": 7,
    "costPerM2": 1,
    "piercingRate": 2,
    "piercingTime": null
  },
  {
    "id": "mat-36",
    "type": "steel",
    "material": "HARDX 450P",
    "thickness": 20,
    "feed": 1100,
    "density": null,
    "cutRate": 7,
    "costPerM2": 1,
    "piercingRate": 2,
    "piercingTime": null
  },
  {
    "id": "mat-175",
    "type": "steel",
    "material": "HARDX 450P",
    "thickness": 25,
    "feed": 900,
    "density": null,
    "cutRate": 7,
    "costPerM2": 1,
    "piercingRate": 2,
    "piercingTime": null
  },
  {
    "id": "mat-117",
    "type": "steel",
    "material": "HARDX 450P",
    "thickness": 32,
    "feed": 650,
    "density": null,
    "cutRate": 7,
    "costPerM2": 10,
    "piercingRate": 6,
    "piercingTime": null
  },
  {
    "id": "mat-78",
    "type": "steel",
    "material": "HARDX 600P",
    "thickness": 0,
    "feed": null,
    "density": null,
    "cutRate": 0,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-170",
    "type": "steel",
    "material": "M/S",
    "thickness": 1,
    "feed": 3000,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 33,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-79",
    "type": "steel",
    "material": "M/S",
    "thickness": 1.6,
    "feed": 3000,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 42,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-173",
    "type": "steel",
    "material": "M/S",
    "thickness": 2,
    "feed": 3000,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 50,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-38",
    "type": "steel",
    "material": "M/S",
    "thickness": 2.5,
    "feed": 3000,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 62,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-58",
    "type": "steel",
    "material": "M/S",
    "thickness": 3,
    "feed": 2300,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 70,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-75",
    "type": "steel",
    "material": "M/S",
    "thickness": 4,
    "feed": 1900,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 92,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-137",
    "type": "steel",
    "material": "M/S",
    "thickness": 5,
    "feed": 1700,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 115,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-138",
    "type": "steel",
    "material": "M/S",
    "thickness": 6,
    "feed": 1500,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 137,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-26",
    "type": "steel",
    "material": "M/S",
    "thickness": 8,
    "feed": 1200,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 182,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-45",
    "type": "steel",
    "material": "M/S",
    "thickness": 10,
    "feed": 1000,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 227,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-86",
    "type": "steel",
    "material": "M/S",
    "thickness": 12,
    "feed": 900,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 272,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-73",
    "type": "steel",
    "material": "M/S",
    "thickness": 16,
    "feed": 650,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 362,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-41",
    "type": "steel",
    "material": "M/S",
    "thickness": 20,
    "feed": 550,
    "density": null,
    "cutRate": 4.5,
    "costPerM2": 475,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-43",
    "type": "STEEL",
    "material": "MS P",
    "thickness": 5,
    "feed": 3500,
    "density": null,
    "cutRate": 7,
    "costPerM2": 165,
    "piercingRate": 0.5,
    "piercingTime": null
  },
  {
    "id": "mat-27",
    "type": "STEEL",
    "material": "MS P",
    "thickness": 6,
    "feed": 2500,
    "density": null,
    "cutRate": 7,
    "costPerM2": 145,
    "piercingRate": 0.5,
    "piercingTime": null
  },
  {
    "id": "mat-18",
    "type": "STEEL",
    "material": "MS P",
    "thickness": 8,
    "feed": 2000,
    "density": null,
    "cutRate": 7,
    "costPerM2": 180,
    "piercingRate": 0.5,
    "piercingTime": null
  },
  {
    "id": "mat-53",
    "type": "STEEL",
    "material": "MS P",
    "thickness": 10,
    "feed": 1600,
    "density": null,
    "cutRate": 7,
    "costPerM2": 210,
    "piercingRate": 0.5,
    "piercingTime": null
  },
  {
    "id": "mat-5",
    "type": "STEEL",
    "material": "MS P",
    "thickness": 12,
    "feed": 1500,
    "density": null,
    "cutRate": 7,
    "costPerM2": 255,
    "piercingRate": 0.5,
    "piercingTime": null
  },
  {
    "id": "mat-88",
    "type": "STEEL",
    "material": "MS P",
    "thickness": 16,
    "feed": 1200,
    "density": null,
    "cutRate": 7,
    "costPerM2": 345,
    "piercingRate": 1,
    "piercingTime": null
  },
  {
    "id": "mat-20",
    "type": "STEEL",
    "material": "MS P",
    "thickness": 20,
    "feed": 1100,
    "density": null,
    "cutRate": 7,
    "costPerM2": 425,
    "piercingRate": 1,
    "piercingTime": null
  },
  {
    "id": "mat-146",
    "type": "STEEL",
    "material": "MS P",
    "thickness": 25,
    "feed": 900,
    "density": null,
    "cutRate": 7,
    "costPerM2": 560,
    "piercingRate": 1,
    "piercingTime": null
  },
  {
    "id": "mat-154",
    "type": "STEEL",
    "material": "MS P",
    "thickness": 28,
    "feed": 750,
    "density": null,
    "cutRate": 7,
    "costPerM2": 586,
    "piercingRate": 1,
    "piercingTime": null
  },
  {
    "id": "mat-3",
    "type": "STEEL",
    "material": "MS P",
    "thickness": 32,
    "feed": 650,
    "density": null,
    "cutRate": 7,
    "costPerM2": 670,
    "piercingRate": 1.5,
    "piercingTime": null
  },
  {
    "id": "mat-94",
    "type": "STEEL",
    "material": "MS P",
    "thickness": 36,
    "feed": 600,
    "density": null,
    "cutRate": 7,
    "costPerM2": 753,
    "piercingRate": 1.5,
    "piercingTime": null
  },
  {
    "id": "mat-77",
    "type": "STEEL",
    "material": "MS P",
    "thickness": 40,
    "feed": 600,
    "density": null,
    "cutRate": 7,
    "costPerM2": 840,
    "piercingRate": 2.5,
    "piercingTime": null
  },
  {
    "id": "mat-35",
    "type": "STEEL",
    "material": "MS P",
    "thickness": 45,
    "feed": 500,
    "density": null,
    "cutRate": 7,
    "costPerM2": 942,
    "piercingRate": 3,
    "piercingTime": null
  },
  {
    "id": "mat-64",
    "type": "STEEL",
    "material": "MS P",
    "thickness": 50,
    "feed": 400,
    "density": null,
    "cutRate": 7,
    "costPerM2": 1045,
    "piercingRate": 3,
    "piercingTime": null
  },
  {
    "id": "mat-24",
    "type": "STEEL",
    "material": "MS P",
    "thickness": 60,
    "feed": 300,
    "density": null,
    "cutRate": 7,
    "costPerM2": 1370,
    "piercingRate": 3,
    "piercingTime": null
  },
  {
    "id": "mat-87",
    "type": "TITANIUM",
    "material": "TITANIUM",
    "thickness": 1,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 0.01,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-198",
    "type": "Unclassified",
    "material": "Test2",
    "thickness": 2,
    "feed": 2222,
    "density": null,
    "cutRate": 2,
    "costPerM2": 2,
    "piercingRate": 0.2,
    "piercingTime": null
  },
  {
    "id": "mat-33",
    "type": "Wear Resistant Steel",
    "material": "OVERLAY",
    "thickness": 16,
    "feed": 1000,
    "density": null,
    "cutRate": 13,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-153",
    "type": "Wear Resistant Steel",
    "material": "OVERLAY",
    "thickness": 20,
    "feed": 1000,
    "density": null,
    "cutRate": 13,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-39",
    "type": "Wear Resistant Steel",
    "material": "OVERLAY",
    "thickness": 24,
    "feed": 1000,
    "density": null,
    "cutRate": 10,
    "costPerM2": 0,
    "piercingRate": 5,
    "piercingTime": null
  },
  {
    "id": "mat-150",
    "type": "Welding Consumable",
    "material": "WELDING",
    "thickness": 1,
    "feed": 1000,
    "density": null,
    "cutRate": 15,
    "costPerM2": 0,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-37",
    "type": "Zincalume Steel",
    "material": "ZINCANEAL",
    "thickness": 0.6,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 15,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-149",
    "type": "Zincalume Steel",
    "material": "ZINCANEAL",
    "thickness": 0.8,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 20,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-99",
    "type": "Zincalume Steel",
    "material": "ZINCANEAL",
    "thickness": 0.9,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 27,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-176",
    "type": "Zincalume Steel",
    "material": "ZINCANEAL",
    "thickness": 1.15,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 30,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-50",
    "type": "Zincalume Steel",
    "material": "ZINCANEAL",
    "thickness": 1.2,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 30,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-163",
    "type": "Zincalume Steel",
    "material": "ZINCANEAL",
    "thickness": 1.6,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 40,
    "piercingRate": 0.1,
    "piercingTime": null
  },
  {
    "id": "mat-12",
    "type": "Zincalume Steel",
    "material": "ZINCANEAL",
    "thickness": 2,
    "feed": 3000,
    "density": null,
    "cutRate": 5.5,
    "costPerM2": 74.5,
    "piercingRate": 0.1,
    "piercingTime": null
  }
];
