create extension if not exists "pgcrypto";

create type public.contact_kind as enum ('client', 'supplier', 'transport', 'staff', 'other');
create type public.quote_status as enum ('draft', 'sent', 'approved', 'inactive', 'converted');
create type public.job_status as enum ('active', 'complete', 'despatch', 'cancelled');
create type public.purchase_status as enum ('open', 'sent', 'received', 'closed');

create table public.contacts (
  id uuid primary key default gen_random_uuid(),
  kind public.contact_kind not null default 'client',
  company_name text not null,
  trading_name text,
  abn text,
  website text,
  email text,
  phone text,
  street_address text,
  suburb text,
  state text,
  postcode text,
  payment_terms text,
  credit_limit numeric(12, 2),
  delivery_notes text,
  delivery_charge numeric(12, 2) default 0,
  stop_supply boolean not null default false,
  approved boolean not null default false,
  status text not null default 'active',
  ai_summary text,
  ai_risks text,
  ai_opportunities text,
  ai_talking_points text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.contact_people (
  id uuid primary key default gen_random_uuid(),
  contact_id uuid not null references public.contacts(id) on delete cascade,
  title text,
  name text not null,
  job_title text,
  direct_phone text,
  mobile text,
  email text,
  created_at timestamptz not null default now()
);

create table public.materials (
  id uuid primary key default gen_random_uuid(),
  material_code text not null,
  material_type text,
  thickness_mm numeric(10, 3) not null,
  stock_size text,
  feed_rate numeric(12, 3),
  cut_rate numeric(12, 3),
  square_meter_rate numeric(12, 3),
  piercing_rate numeric(12, 3),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (material_code, thickness_mm, stock_size)
);

create table public.quotes (
  id uuid primary key default gen_random_uuid(),
  quote_number bigint generated by default as identity unique,
  contact_id uuid references public.contacts(id),
  sales_staff_id uuid references public.contact_people(id),
  quote_date date not null default current_date,
  status public.quote_status not null default 'draft',
  delivery_charge numeric(12, 2) not null default 0,
  subtotal numeric(12, 2) not null default 0,
  gst numeric(12, 2) not null default 0,
  total_inc_gst numeric(12, 2) not null default 0,
  notes text,
  approved_by text,
  valid_until date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.quote_lines (
  id uuid primary key default gen_random_uuid(),
  quote_id uuid not null references public.quotes(id) on delete cascade,
  line_no integer not null,
  program_no text,
  part_number text,
  description text not null,
  material_id uuid references public.materials(id),
  free_material boolean not null default false,
  quantity numeric(12, 3) not null default 1,
  material_cost numeric(12, 2) not null default 0,
  cutting_cost numeric(12, 2) not null default 0,
  piercing_cost numeric(12, 2) not null default 0,
  other_cost numeric(12, 2) not null default 0,
  unit_price numeric(12, 2) not null default 0,
  line_total numeric(12, 2) not null default 0,
  weight_kg numeric(12, 3),
  laser_minutes numeric(12, 3),
  plasma_minutes numeric(12, 3),
  status text not null default 'quote',
  unique (quote_id, line_no)
);

create table public.quote_operations (
  id uuid primary key default gen_random_uuid(),
  quote_line_id uuid not null references public.quote_lines(id) on delete cascade,
  operation_type text not null,
  od_id text,
  count numeric(12, 3),
  diameter numeric(12, 3),
  side_1 numeric(12, 3),
  side_2 numeric(12, 3),
  length numeric(12, 3),
  perimeter_total numeric(12, 3),
  weight_kg numeric(12, 3)
);

create table public.jobs (
  id uuid primary key default gen_random_uuid(),
  job_number bigint generated by default as identity unique,
  quote_id uuid references public.quotes(id),
  contact_id uuid references public.contacts(id),
  job_date date not null default current_date,
  due_date date,
  order_number text,
  status public.job_status not null default 'active',
  myob_invoice_number text,
  myob_invoice_date date,
  email_sent_at timestamptz,
  despatched_at timestamptz,
  completed_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.material_orders (
  id uuid primary key default gen_random_uuid(),
  job_id uuid references public.jobs(id),
  contact_id uuid references public.contacts(id),
  required_date date,
  material text not null,
  thickness_mm numeric(10, 3),
  stock_size text,
  quantity numeric(12, 3) not null default 1,
  ordered boolean not null default false,
  purchase_order_no text,
  supplier_id uuid references public.contacts(id),
  notes text,
  received boolean not null default false,
  status text not null default 'open',
  created_at timestamptz not null default now()
);

create table public.purchase_orders (
  id uuid primary key default gen_random_uuid(),
  lpo_number bigint generated by default as identity unique,
  supplier_id uuid references public.contacts(id),
  order_date date not null default current_date,
  required_date date,
  supplier_reference text,
  status public.purchase_status not null default 'open',
  comments_for_supplier text,
  subtotal numeric(12, 2) not null default 0,
  delivery numeric(12, 2) not null default 0,
  gst numeric(12, 2) not null default 0,
  total_inc_gst numeric(12, 2) not null default 0,
  created_at timestamptz not null default now()
);

create table public.invoices (
  id uuid primary key default gen_random_uuid(),
  invoice_number bigint generated by default as identity unique,
  job_id uuid references public.jobs(id),
  contact_id uuid references public.contacts(id),
  invoice_date date,
  myob_reference text,
  status text not null default 'pending',
  subtotal numeric(12, 2) not null default 0,
  delivery numeric(12, 2) not null default 0,
  gst numeric(12, 2) not null default 0,
  total_inc_gst numeric(12, 2) not null default 0,
  sent_at timestamptz,
  notes text,
  created_at timestamptz not null default now()
);

alter table public.contacts enable row level security;
alter table public.contact_people enable row level security;
alter table public.materials enable row level security;
alter table public.quotes enable row level security;
alter table public.quote_lines enable row level security;
alter table public.quote_operations enable row level security;
alter table public.jobs enable row level security;
alter table public.material_orders enable row level security;
alter table public.purchase_orders enable row level security;
alter table public.invoices enable row level security;

create policy "Authenticated users can read contacts" on public.contacts for select to authenticated using (true);
create policy "Authenticated users can read contact people" on public.contact_people for select to authenticated using (true);
create policy "Authenticated users can read materials" on public.materials for select to authenticated using (true);
create policy "Authenticated users can read quotes" on public.quotes for select to authenticated using (true);
create policy "Authenticated users can read quote lines" on public.quote_lines for select to authenticated using (true);
create policy "Authenticated users can read quote operations" on public.quote_operations for select to authenticated using (true);
create policy "Authenticated users can read jobs" on public.jobs for select to authenticated using (true);
create policy "Authenticated users can read material orders" on public.material_orders for select to authenticated using (true);
create policy "Authenticated users can read purchase orders" on public.purchase_orders for select to authenticated using (true);
create policy "Authenticated users can read invoices" on public.invoices for select to authenticated using (true);
